// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAetNR4BhxY9moIr4jUkI2GeybpHNptJ7w',
    appId: '1:1029843182429:web:fd3402e9eb6291d92dfeb4',
    messagingSenderId: '1029843182429',
    projectId: 'gtickets-789ea',
    authDomain: 'gtickets-789ea.firebaseapp.com',
    storageBucket: 'gtickets-789ea.appspot.com',
    measurementId: 'G-309RNVC6TB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe5fzEkI_uO8xaVdMF4skT_3TdRHn7RUo',
    appId: '1:1029843182429:android:abeef2709da3982b2dfeb4',
    messagingSenderId: '1029843182429',
    projectId: 'gtickets-789ea',
    storageBucket: 'gtickets-789ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1boHbRdyckAyYrTRm3u4ijiC2N_ODh48',
    appId: '1:1029843182429:ios:e6254beeca665ff72dfeb4',
    messagingSenderId: '1029843182429',
    projectId: 'gtickets-789ea',
    storageBucket: 'gtickets-789ea.appspot.com',
    iosBundleId: 'com.example.gestionDesTickets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1boHbRdyckAyYrTRm3u4ijiC2N_ODh48',
    appId: '1:1029843182429:ios:e6254beeca665ff72dfeb4',
    messagingSenderId: '1029843182429',
    projectId: 'gtickets-789ea',
    storageBucket: 'gtickets-789ea.appspot.com',
    iosBundleId: 'com.example.gestionDesTickets',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAetNR4BhxY9moIr4jUkI2GeybpHNptJ7w',
    appId: '1:1029843182429:web:61f9f769bf5635652dfeb4',
    messagingSenderId: '1029843182429',
    projectId: 'gtickets-789ea',
    authDomain: 'gtickets-789ea.firebaseapp.com',
    storageBucket: 'gtickets-789ea.appspot.com',
    measurementId: 'G-V7T7WNSNX2',
  );
}
